apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: lekt
    component: backend
spec:
  type: ClusterIP
  selector:
    app: lekt
    component: backend
  ports:
    - port: 8000
