version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - actions-dependencies
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/backend"
    labels:
      - backend-dependencies
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - frontend-dependencies
    versioning-strategy: widen
