version: "3.8"
services:
  backend:
    image: lekt-backend-image
    # build:
    #   context: ./backend
    #   # TODO 27/03/20 psacawa: figure out why this doesn't work
    networks: [lekt_net]
    depends_on:
      - rdb
      - cache
    restart: always
    ports:
      - 18000:8000
    volumes:
      - ./backend/assets:/code/assets
    environment:
      # DJANGO_AWS_ACCESS_KEY_ID:
      # DJANGO_AWS_SECRET_ACCESS_KEY:
      DJANGO_ENV: prod
      DJANGO_DATABASE: todos
      DJANGO_POSTGRES_HOST: rdb
      DJANGO_POSTGRES_PASSWORD: django-pass
      DJANGO_REDIS_HOST: cache
      # DJANGO_SECRET_KEY:
  cache:
    image: redis:6.2
    networks: [lekt_net]
    ports:
      - 16379:6379
    restart: always
  rdb:
    image: postgres:13
    networks: [lekt_net]
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: lekt_db
      POSTGRES_USER: lekt_user
      POSTGRES_PASSWORD: django-pass
    restart: always
networks:
  lekt_net:
    name: lekt_net
    driver: bridge
