version: "3.8"
services:
  proxy:
    build:
      context: ./frontend
      network: lekt_net
    networks: [lekt_net]
    ports:
      - 81:80
    depends_on:
      - app
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx.site.conf:/etc/nginx/sites-enabled/lekt
    restart: always
  app:
    build:
      context: ./backend
      # TODO 27/03/20 psacawa: figure out why this doesn't work
      network: lekt_net
    networks: [lekt_net]
    depends_on:
      - db
      - cache
    restart: always
    ports:
      - 8001:8000
    volumes:
      - ./backend/assets:/code/assets
    environment:
      DJANGO_ENV: test
      POSTGRES_HOST: db
      DJANGO_CACHE_HOST: redis
    env_file:
      - .env.secret
  cache:
    image: redis:latest
    networks: [lekt_net]
    ports:
      - 6380:6379
    restart: always
  db:
    image: postgres:latest
    networks: [lekt_net]
    ports:
      - 5433:5432
    # volumes:
    #   - db-volume:./
    environment:
      POSTGRES_DB: lekt_db
      POSTGRES_USER: lekt_user
    env_file:
      - .env.secret
    restart: always
  # debug:
  #   image: nicolaka/netshoot
  #   stdin_open: true
  #   tty: true
  #   entrypoint: bash
networks:
  lekt_net:
    name: lekt_net
    driver: bridge
volumes:
  db_volume:
