version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-backend:
    executor: python/default
    steps:
      - checkout
      - run: cd backend
      - run: pip install poetry
      - run: poetry install
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - test-backend
