version: 2.1

orbs:
  python: circleci/python@1.3.2

workflows:
  main:
    jobs:
      - python/test:
          app-dir: backend
          pkg-manager: poetry
          version: "3.9"
          test-tool: "pytest"
