# Generated by Django 3.2.5 on 2021-08-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_2_5"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="checkout_sessions",
            field=models.ManyToManyField(
                help_text="Currently open checkout sessions for the user. Necessary for the view confirning the checkout to be able to affiliate a subscription with the user attached to the corresponding session.",
                to="djstripe.Session",
                verbose_name="Open checkout sessions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                help_text="Stripe Plan (really newer API Price) attached to User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.subscription",
                verbose_name="Plan",
            ),
        ),
    ]
