# Generated by Django 3.2.6 on 2021-08-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_profile_image",
            field=models.BooleanField(default=False),
        ),
    ]
