# Generated by Django 3.1.4 on 2021-01-10 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lexeme",
            name="polymorphic_ctype",
        ),
        migrations.AddField(
            model_name="lexeme",
            name="linguisticfeature_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="lekt.linguisticfeature",
            ),
            preserve_default=False,
        ),
    ]
