# Generated by Django 3.2.6 on 2021-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="featureweight",
            unique_together={("base_lang", "target_lang", "feature", "phrasepair")},
        ),
        migrations.AlterUniqueTogether(
            name="lexemeweight",
            unique_together={("base_lang", "target_lang", "lexeme", "phrasepair")},
        ),
        migrations.AlterUniqueTogether(
            name="observableweight",
            unique_together={("base_lang", "target_lang", "observable", "phrasepair")},
        ),
    ]
