# Generated by Django 3.1.4 on 2021-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="morph",
            field=models.CharField(
                default="",
                help_text="computed as str(Token.morph)",
                max_length=200,
                verbose_name="Concentaion of morphological features, represents FEATS in CoNLL-u",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="word",
            name="tag",
            field=models.CharField(
                help_text="computed as Token.tag_,\n        e.g. JJ, ADJ, ...",
                max_length=200,
                verbose_name="Detailed part of speech, represents XPOS in CoNLL-u if present",
            ),
        ),
    ]
