# Generated by Django 3.1.4 on 2020-12-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0002_initialize_aws_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="phraseword",
            name="end",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phraseword",
            name="start",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
