# Generated by Django 3.2.6 on 2021-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0002_auto_20210827_1416"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lexemeweight",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="observableweight",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="lexemeweight",
            constraint=models.UniqueConstraint(
                fields=("base_lang", "target_lang", "lexeme", "phrasepair"),
                name="lekt_lexeme_weight_unique",
            ),
        ),
    ]
