# Generated by Django 3.1.4 on 2021-01-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0002_auto_20201220_2234"),
    ]

    operations = [
        migrations.CreateModel(
            name="LexemeWeight",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("weight", models.FloatField(default=0.0)),
                (
                    "base_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="lekt.language",
                    ),
                ),
                (
                    "lexeme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="lekt.lexeme"
                    ),
                ),
                (
                    "phrasepair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexeme_weights",
                        to="lekt.phrasepair",
                    ),
                ),
                (
                    "target_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="lekt.language",
                    ),
                ),
            ],
            options={
                "db_table": "lekt_lexeme_weight",
                "managed": True,
            },
        ),
    ]
