# Generated by Django 3.1.4 on 2021-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0002_auto_20201220_2234"),
    ]

    operations = [
        migrations.CreateModel(
            name="LexemeWeight",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("weight", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "lekt_lexeme_weight",
                "managed": False,
            },
        ),
    ]
