# Generated by Django 3.1.4 on 2021-01-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0002_auto_20210110_0339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationweight",
            name="annotation",
            field=models.ForeignKey(
                db_column="annot_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="lekt.annotation",
            ),
        ),
    ]
