# Generated by Django 3.2.6 on 2021-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0003_auto_20210827_1525"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="observableweight",
            constraint=models.UniqueConstraint(
                fields=("base_lang", "target_lang", "observable", "phrasepair"),
                name="asdf",
            ),
        ),
    ]
