# Generated by Django 3.1.4 on 2021-01-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0003_auto_20210110_0636"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="linguisticfeature_ptr",
        ),
        migrations.RemoveField(
            model_name="lexeme",
            name="linguisticfeature_ptr",
        ),
        migrations.AddField(
            model_name="annotation",
            name="feature_ptr",
            field=models.OneToOneField(
                db_column="feature_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="lekt.linguisticfeature",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lexeme",
            name="feature_ptr",
            field=models.OneToOneField(
                db_column="feature_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="lekt.linguisticfeature",
            ),
            preserve_default=False,
        ),
    ]
