# Generated by Django 3.1.4 on 2021-02-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0004_auto_20210210_2226"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscription",
            new_name="LanguageSubscription",
        ),
        migrations.CreateModel(
            name="TrackedObservable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="time of update"),
                ),
                (
                    "difficulty",
                    models.FloatField(
                        default=1.0,
                        help_text="Relative weights of the observable during scheduling",
                    ),
                ),
                ("last_answered_at", models.DateTimeField()),
                (
                    "observable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="lekt.observable",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lekt.languagesubscription",
                        verbose_name="Tracking Record",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "observable")},
            },
        ),
    ]
