# Generated by Django 3.1.4 on 2021-01-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0004_auto_20210110_0831"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LinguisticFeatureWeight",
            new_name="FeatureWeight",
        ),
    ]
