# Generated by Django 3.1.4 on 2021-02-13 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0005_auto_20210213_2128"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="time of update"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lekt.languagesubscription",
                        verbose_name="Language Subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="trackedobservable",
            name="list",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lekt.trackedlist",
                verbose_name="Tracking List",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="trackedobservable",
            unique_together={("list", "observable")},
        ),
        migrations.RemoveField(
            model_name="trackedobservable",
            name="subscription",
        ),
    ]
