# Generated by Django 3.2.6 on 2021-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0005_auto_20210827_1535"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="featureweight",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="featureweight",
            constraint=models.UniqueConstraint(
                fields=("base_lang", "target_lang", "feature", "phrasepair"),
                name="lekt_featureweight_unique",
            ),
        ),
    ]
