# Generated by Django 3.1.4 on 2021-01-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0005_auto_20210110_1101"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="explanation",
            new_name="description",
        ),
    ]
