# Generated by Django 3.1.4 on 2021-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0006_auto_20210213_2139"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedlist",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
