# Generated by Django 3.1.4 on 2021-02-14 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0007_trackedlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedobservable",
            name="tracked_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observables",
                to="lekt.trackedlist",
                verbose_name="Tracking List",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="languagesubscription",
            name="owner",
            field=models.ForeignKey(
                help_text="UserProfile of the account owning the subscription",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_set",
                to="lekt.userprofile",
                verbose_name="Owner's profile",
            ),
        ),
        migrations.AlterField(
            model_name="trackedobservable",
            name="last_answered_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="trackedobservable",
            unique_together={("tracked_list", "observable")},
        ),
        migrations.RemoveField(
            model_name="trackedobservable",
            name="list",
        ),
    ]
