# Generated by Django 3.1.4 on 2021-02-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0008_auto_20210214_2343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="id",
        ),
        migrations.RemoveField(
            model_name="lexeme",
            name="id",
        ),
        migrations.AlterField(
            model_name="feature",
            name="observable_ptr",
            field=models.OneToOneField(
                db_column="observable_id",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="lekt.observable",
            ),
        ),
        migrations.AlterField(
            model_name="lexeme",
            name="observable_ptr",
            field=models.OneToOneField(
                db_column="observable_id",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="lekt.observable",
            ),
        ),
    ]
