# Generated by Django 3.1.4 on 2021-02-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0012_auto_20210217_2040"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trackedlist",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="trackedlist",
            unique_together={("subscription", "name")},
        ),
    ]
