# Generated by Django 3.1.4 on 2021-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0014_add_primary_keys_to_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="active",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
