# Generated by Django 3.1.4 on 2021-03-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0015_language_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lexeme",
            name="pos",
            field=models.CharField(
                choices=[
                    ("ADJ", "adjective"),
                    ("ADP", "adposition"),
                    ("ADV", "adverb"),
                    ("AUX", "auxiliary"),
                    ("CCONJ", "conjunction"),
                    ("DET", "determiner"),
                    ("INTJ", "interjection"),
                    ("NOUN", "noun"),
                    ("NUM", "numeral"),
                    ("PART", "particle"),
                    ("PRON", "pronoun"),
                    ("PROPN", "proper noun"),
                    ("PUNCT", "punctuation"),
                    ("SCONJ", "conjunction"),
                    ("SYM", "symbol"),
                    ("VERB", "verb"),
                ],
                help_text="computed as Token.pos_",
                max_length=50,
                verbose_name="Part of speech",
            ),
        ),
        migrations.AlterField(
            model_name="trackedlist",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to="lekt.languagesubscription",
                verbose_name="Language Subscription",
            ),
        ),
    ]
