# Generated by Django 3.1.4 on 2021-03-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0016_auto_20210316_2018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagesubscription",
            name="owner",
            field=models.ForeignKey(
                help_text="UserProfile of the account owning the subscription",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="lekt.userprofile",
                verbose_name="Owner's profile",
            ),
        ),
    ]
