# Generated by Django 3.1.4 on 2021-03-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0017_auto_20210316_2023"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackedobservable",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="trackedobservable",
            name="score",
            field=models.FloatField(
                default=0, help_text="Cumulative score of the observable"
            ),
        ),
    ]
