# Generated by Django 3.2.3 on 2021-07-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0018_auto_20210318_1927"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpus",
            options={},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={},
        ),
        migrations.AlterModelOptions(
            name="phrase",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="voice",
            options={},
        ),
    ]
