# Generated by Django 3.2.3 on 2021-07-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_2_5"),
        ("lekt", "0020_userprofile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="customer",
            field=models.ForeignKey(
                help_text="Stripe Customer attached to UserProfile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan",
            field=models.ForeignKey(
                help_text="Stripe Plan (really newer API Price) at to UserProfile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.price",
                verbose_name="Plan",
            ),
        ),
    ]
