# Generated by Django 3.2.5 on 2021-08-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_2_5"),
        ("lekt", "0021_auto_20210724_0610"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="customer",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="checkout_sessions",
            field=models.ManyToManyField(
                help_text="Stripe Checkout sessions attached to UserProfile",
                to="djstripe.Session",
                verbose_name="Checkout Sessions",
            ),
        ),
    ]
