# Generated by Django 3.2.5 on 2021-08-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_2_5"),
        ("lekt", "0022_auto_20210802_1832"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="plan",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_subscription",
            field=models.ForeignKey(
                help_text="Stripe Plan (really newer API Price) at to UserProfile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.subscription",
                verbose_name="Plan",
            ),
        ),
    ]
