# Generated by Django 3.2.5 on 2021-08-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lekt", "0023_auto_20210802_2204"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="checkout_sessions",
        ),
    ]
