# Generated by Django 3.2.5 on 2021-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_2_5"),
        ("lekt", "0023_auto_20210802_2204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="checkout_sessions",
            field=models.ManyToManyField(
                help_text="Currently open checkout sessions for the user. Necessary for the view confirning the checkout to be able to affiliate a subscription with the user attached to the corresponding session.",
                to="djstripe.Session",
                verbose_name="Open checkout sessions",
            ),
        ),
    ]
