resources:
  - ../../base

commonLabels:
  env: staging

nameSuffix: -staging

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: lekt-backend-staging
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-1
        value:
          name: DJANGO_DOMAIN
          value: dev.lex.quest
