apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lekt
  region: us-east-2

managedNodeGroups:
  - name: ng-spot
    instanceType: t2.medium
    spot: true
    # niestandardowy ami powoduje problemy
    # ami: ami-00399ec92321828f5
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: True
      publicKeyPath: ~/.ssh/lektprojekt-cluster-key.pub
    availabilityZones:
      - us-east-2c
