apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lektprojekt-assets
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: lektprojekt-assets
