name: Build and push docker images to AWS

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        context: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: docker/login-action@v1
        with:
          registry: 886185890074.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: 886185890074.dkr.ecr.us-east-2.amazonaws.com/lektprojekt-${{ matrix.context}}-image:latest
