name: build-backend

on:
  push:
    branches:
      - master
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to AWS
        uses: docker/login-action@v1
        with:
          registry: 886185890074.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          tags: |
            886185890074.dkr.ecr.us-east-2.amazonaws.com/lekt-backend-image:latest
            886185890074.dkr.ecr.us-east-2.amazonaws.com/lekt-backend-image:${{ github.sha }}
