name: build-frontend

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/build-frontend.yaml
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    env:
      NODE_ENV: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo REACT_GIT_HASH=${{ github.sha }} >> frontend/.env.production
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to AWS
        uses: docker/login-action@v1
        with:
          registry: 886185890074.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            886185890074.dkr.ecr.us-east-2.amazonaws.com/lekt-frontend-image:latest
            886185890074.dkr.ecr.us-east-2.amazonaws.com/lekt-frontend-image:${{ github.sha }}
