name: test-backend

on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/test-backend.yaml
  workflow_dispatch:

jobs:
  test:
    env:
      DJANGO_ENV: test
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: lekt_admin
          POSTGRES_PASSWORD: django-pass
          POSTGRES_DB: test_lekt_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: backend-${{ hashFiles('backend/poetry.lock') }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies
        run: |
          poetry export --without-hashes -o requirements.txt
          pip install -r requirements.txt
        working-directory: backend
      - name: Prepare database
        run: |
          python3 manage.py migrate
          python3 manage.py loaddata assets/test_fixture.json
        working-directory: backend
      - name: Pytest
        run: pytest
        working-directory: backend
